ibm:
  mq:
    queue-manager: ${IBM_MQ_QUEUE_MANAGER:QM1}
    channel: ${IBM_MQ_CHANNEL:DEV.APP.SVRCONN}
    conn-name: "${IBM_MQ_HOST:ibmmq}(${IBM_MQ_PORT:1414})"
    user: ${IBM_MQ_USER:app}
    password: ${IBM_MQ_PASSWORD:passw0rd}

app:
  mq:
    dlq: ${IBM_MQ_DLQ:DEV.DEAD.LETTER.QUEUE}

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: ${MANAGEMENT_TRACING_PROPAGATION_TYPE:W3C}
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
    metrics:
      export:
        url: ${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://localhost:4318}
        step: 30s
